pull_request_rules:
   - name: automatic merge when author is dependabot
     conditions:
       - author=dependabot[bot]
       - check-success=test (3.9)
       - check-success=test (3.10)
       - base=main
     actions:
       merge:
         method: rebase
