name: Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
           flake8 garminworkouts tests

      - name: Test with pytest
        run: |
          pytest --cov=garminworkouts --cov-report=xml tests

      - name: Upload test coverage results
        uses: codecov/codecov-action@v3
        with:
          env_vars: PYTHON_VERSION
