name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: flake8 garminworkouts tests

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: pytest --cov=garminworkouts --cov-report=xml tests
      - uses: codecov/codecov-action@v3
        with:
          env_vars: PYTHON_VERSION

  required-checks:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: exit 0

  dependabot:
    runs-on: ubuntu-latest
    needs: [required-checks]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    permissions:
      pull-requests: write
      contents: write

    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - run: gh pr review --approve "$PR_URL"
      - run: gh pr merge --auto --merge "$PR_URL"
